sudo: required
language: 
 - cpp
dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
- sudo apt-get install libboost-all-dev -y
- sudo apt-get install libgtest-dev -y
- cd /usr/src/gtest
- sudo env "PATH=$PATH" cmake .
#- sudo env "PATH=$PATH" cmake --build . --target install
- sudo make
- sudo cp *.a /usr/lib
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- cd $TRAVIS_BUILD_DIR

script:
- CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .
- CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake --build .
- CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake --build . --target test
- CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvladimirsuvorov:$BINTRAY_API_KEY "https://api.bintray.com/content/vladimirsuvorov/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
