sudo: required
language: cpp
 

#matrix:
# include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
- eval "${MATRIX_EVAL}"
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq

#- sudo apt-get install libspdlog-dev -y
- echo "PWD:"
- echo $PWD
- echo "TRAVIS_BUILD_DIR:"
- echo $TRAVIS_BUILD_DIR
- sudo apt install libgtest-dev cmake -y
- cd /usr/src/gtest
- sudo cmake .
- sudo cmake --build .
- sudo cp *.a /usr/lib
- cd ${TRAVIS_BUILD_DIR}
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script: 
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvladimirsuvorov:$BINTRAY_API_KEY "https://api.bintray.com/content/vladimirsuvorov/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
